### ISSUE TITLE
License

### ISSUE THREAD

**Issue by garrensmith** [tkafka/react-VelocityTransitionGroup#1]
Hi @tkafka 

I see you authored this https://gist.github.com/tkafka/0d94c6ec94297bb67091. Its really great and I was investigating using it in CouchDB's web UI [Fauxton](https://github.com/apache/couchdb-fauxton). Could you add a license to that file. I cannot use it unless its under an open source license.

Cheers
Garren

**Comment by tkafka** [comment]
Awesome! There you go, MIT license should be ok, right?

Happy to have helped :) 
Tomas

**Comment by garrensmith** [comment]
Perfect thanks.
